### ISSUE TITLE
This is awesome! A couple of questions.

### ISSUE THREAD

**Issue by petebytes** [code-and-effect/effective_test_bot#1]
My dev environment is running in docker contaiiners using docker-compose.
- Would I modify the test_helper.rb after installation?
- Is it possible to use mini_magick instead or rmagik?

**Comment by matt-riemer** [comment]
Hey @petebytes 

1.) Yes. You could modify the `test_helper.rb` and/or `application_system_test_case.rb` file to get it working for your specific rails app.

If you can do a `rails test:system` and `visit(root_url)` that's probably all you need.

2.) I have removed `rmagick` as a hard dependency of this gem, and made it optional.

Right now you need rmagick just to do the animated gif portion of the gem.

All the other testing, screenshots, etc, will work without it.

I tried really hard to implement an animated gif via the newer`gem 'image_processing'` and `ImageProcessing::MiniMagick` to produce an animated gif, but I don't know now.  I couldn't find any examples of it :)

But, ugh..you don't need `rmagick` anymore! Yay.

3.) I have given this gem some love today to upgrade it for rails 6.0.0.rc1 support.

You should try to install the latest version `effective_test_bot 1.1.0` and check out some of the config files there.

4.) Good luck, I'd love to hear how you use this gem!

**Comment by matt-riemer** [comment]
Additionally:

Please see

https://github.com/code-and-effect/effective_test_bot/tree/master/config

for some "works for me" config files :)

As well as,

https://github.com/code-and-effect/effective_website

for an example app with this gem implemented.

Cheers!

**Comment by petebytes** [comment]
Thanks for all the detail - I tried to get this going today but failed :(
I will open a separate issue
