### ISSUE TITLE
Don't know how to build task 'test:bot:environment'

### ISSUE THREAD

**Issue by petebytes** [code-and-effect/effective_test_bot#2]
Rails 6.0.0.rc1
Ruby 2.6.3p62

- Added the Gem
- Added users fixture
- Tried docker-compose exec web bin/rails test:bot:environment
- failed with Don't know how to build task 'test:bot:environment'

I will try this again later, reverted my environment before capturing the stack track :(

**Comment by matt-riemer** [comment]
Okay, yea something weird with your Gemfile or Rakefile maybe?

Pretty sure the rake task should at least run. Is it present in `rake -T` ?

**Comment by petebytes** [comment]
It was not present in rake -T
