### ISSUE TITLE
non-crud routes seem wrong

### ISSUE THREAD

**Issue by jdar** [code-and-effect/effective_test_bot#3]
Defining additional routes causes strange test errors. Specifically, it seems to be running collection-routes on the wrong urls?

Below, I have some simple examples from an app forked from effective_website. (Two different variations on defining custom collection routes.)

Usually I might do something like this:

```
resource :products do
  collection do
      get :search
      get :data  # example for a json route.
  end
end
```

This causes errors in BOTH  "test:bot:environment" AND "test:bot"

So I tried an intervention.  
```
for route_token in ["data","search"]
    match "/users/#{route_token}", to: "products##{route_token}", via: [:get], as: :"users_#{route_token}_products"
    match "/"+route_token, to: "products##{route_token}", via: [:get], as: :"#{route_token}_products"
  end
```

As you can see, the intervention is to construct the routes manually, and redundantly. Under this intervention "test:bot:environment" is all green, and fewer errors for "test:bot"

Ok, now looking at the error.
```
  crud_test: (mates#create_valid)                                ERROR (2.15s)
ActionController::RoutingError:         ActionController::RoutingError: No route matches [GET] "/mates/data.json"
```

Wait, what? Why would it think "Mates#data" exists?

I'll add more comments as I explore the issue.

**Comment by rollyar** [comment]
Have this error on rails test:bot:environmet and not found solution, can help me?

test_08:_capybara_database_connection_is_shared                ERROR (0.51s)
Minitest::UnexpectedError:         NoMethodError: undefined method `screenshots=' for EffectiveTestBot:Module
        Did you mean?  screenshots
                       screenshots?
            effective_test_bot (1.2.7) test/support/effective_test_bot_screenshots_helper.rb:46:in `ensure in without_screenshots'
            effective_test_bot (1.2.7) test/support/effective_test_bot_screenshots_helper.rb:46:in `without_screenshots'
            effective_test_bot (1.2.7) test/test_bot/system/environment_test.rb:56:in `block in <class:EnvironmentTest>
