### ISSUE TITLE
test_08:_capybara_database_connection_is_shared ERROR

### ISSUE THREAD

**Issue by rollyar** [code-and-effect/effective_test_bot#4]
Have problems with  test 08 when run rails test:bot:environment. can help me?
this is the log.

Minitest::UnexpectedError:         NoMethodError: undefined method `screenshots=' for EffectiveTestBot:Module
        Did you mean?  screenshots
                       screenshots?
            effective_test_bot (1.2.9) test/support/effective_test_bot_screenshots_helper.rb:46:in `ensure in without_screenshots'
            effective_test_bot (1.2.9) test/support/effective_test_bot_screenshots_helper.rb:46:in `without_screenshots'
            effective_test_bot (1.2.9) test/test_bot/system/environment_test.rb:56:in `block in <class:EnvironmentTest>'
            railties (6.1.4.1) lib/rails/test_unit/line_filtering.rb:10:in `run'

Many tanks.

**Comment by matt-riemer** [comment]
Hey

Thanks for the heads up!

Please upgrade `effective_resources` gem to `1.8.38` the fix is actually in there :)

Cheers
